### ISSUE TITLE
Vytvorit tabulku vozidel

### ISSUE THREAD

**Issue by milant007** [zauzoo/db#1]
### Tabulka vozidel by mela obsahovat tyto sloupce
- vazba do Party
- SPZ - varchar(15)
- VIN - varchar(30)
- Znacka, zde se bude jednat o VOLVO a Renault, obecne vsechny znacky vozidel - takze asi vazba do ciselniku
- Druh vozidla, zde pouze Tahač, obecne Tahac/Naves/Bus/atd. - mozna taky vazba do ciselniku?
- Model varchar(20)
- UnitNr - pouze pro potreby Volva cislo pod jakym je auto vedene ve VOLVO db
- Datum uvedeni vozidla do provozu

**Comment by jzelenka** [comment]
budeme mit grid "vsechna vozidla" (krome gridu u zakaznika) ?
pokud jo, kde bude v hlavnim menu?

**Comment by milant007** [comment]
urcite vlastni grid - mam nad tim gridem funkce na automaticke prirazovani balicku(sluzeb) pro vybrana vozidla. cili nejak zafiltrujeme, vybereme auta a pustime funkci...
asi i vlastni menu menu treba Machine a tam pak Cars? Nebo zatim primo Cars?

**Comment by jzelenka** [comment]
Ok,
Assets / Cars

**Comment by jzelenka** [comment]
create sequence seq_dpr_vehicle start 1 increment 50
 ; 


    create table cpr_vehicle_brand (
        vehicle_brand_id int4 not null,
        date_created timestamp default CURRENT_TIMESTAMP not null,
        date_updated timestamp,
        user_created varchar(50) default 'system' not null,
        user_updated varchar(50),
        tenant_id int4 not null,
        name varchar(100),
        primary key (vehicle_brand_id)
    )
 ; 

    create table cpr_vehicle_type (
        vehicle_type_id int4 not null,
        date_created timestamp default CURRENT_TIMESTAMP not null,
        date_updated timestamp,
        user_created varchar(50) default 'system' not null,
        user_updated varchar(50),
        tenant_id int4 not null,
        name varchar(100),
        primary key (vehicle_type_id)
    )
 ; 


 
    create table dpr_vehicle (
        vehicle_id int4 not null,
        date_created timestamp default CURRENT_TIMESTAMP not null,
        date_updated timestamp,
        user_created varchar(50) default 'system' not null,
        user_updated varchar(50),
        tenant_id int4 not null,
        activation_date date,
        model varchar(20),
        registration_number varchar(15),
        vehicle_number varchar(30),
        vin varchar(30),
        party_id int4,
        vehicle_brand_id int4,
        vehicle_type_id int4,
        primary key (vehicle_id)
    )
 ; 

     create index idx_dpr_vehicle_01 on dpr_vehicle (vehicle_number)
 ; 

    alter table dpr_vehicle 
        add constraint fk_dpr_vehicle_01 
        foreign key (party_id) 
        references dpa_party
 ; 

    alter table dpr_vehicle 
        add constraint fk_dpr_vehicle_02 
        foreign key (vehicle_brand_id) 
        references cpr_vehicle_brand
 ; 

    alter table dpr_vehicle 
        add constraint fk_dpr_vehicle_03 
        foreign key (vehicle_type_id) 
        references cpr_vehicle_type
 ;

**Comment by jzelenka** [comment]
registration_number  je spz
UnitNr je vehicle_number 

cpr_vehicle_brand a cpr_vehicle_type jsou tenant GLOBAL  ( = do tenant_id dej 0)
dpr_vehicle je PRIVATE (tenant_id = 1)

napln si druh vozidla - cpr_vehicle_type 

a znacku vozidla - cpr_vehicle_brand 
Znacku jsem udelal jako jednoduchy ciselnik, ackoliv je to mozna hiearchie:
znacka - model
Opel - Insignia
Skoda - Superb

... zatim to neresim.

**Comment by milant007** [comment]
Je to naimportovane. Datum registrace se mi sice pri prenosu 1:1 mezi db rozsypal a ja si toho nevsiml, ale nema takovy vyznam, abych ted znova prenasel 5000 zaznamu.

**Comment by jzelenka** [comment]
hotovo, nasazeno
