### ISSUE TITLE
duplicity ICO

### ISSUE THREAD

**Issue by jzelenka** [zauzoo/db#2]
Radky v party maji byt unikatni osoby (pravnicke nebo fyzicke).

zkusil jsem vytvorit:
alter table dpa_party add constraint uc_dpa_party_01 unique (ico)

a jsou tam duplicity:

select ico, count(*) from dpa_party group by ico having count(*) > 1

**Comment by milant007** [comment]
duplicity ICO jsem odstranil a zalozil unique index

**Comment by jzelenka** [comment]
pri splneni muzes bug zavrit..
