### ISSUE TITLE
Návrh fakturačního modulu

### ISSUE THREAD

**Issue by milant007** [zauzoo/db#3]
#### Hlavička FA seznam nutnych poli - vypíšu pole pouze co využívá VOLVO, ostatní budeme přidávat
- vazba do party, odběratel
- VS varchar(20), ale muze byt i vice, google FA jsou hodne dlouhy.
- Datum vystavení(datetime?), na FA i ve formuláři bude sice pouze datum, ale mockrát jsem se setkal, že jsem potřeboval vědět čas vystavení
- DUZP(date)
- měna - vazba do cpa_currency, default se dotáhne ze dpa_party
- kurz(numeric) - dotáhne se podle Datumu vystavení. Tabulku kurzu by bylo dobré si denně stahovat do DB z ČNB nebo možnost si ji vyplňovat ručně, mohou používat jiný kurz než ČNB. asi nějaká child tabulka k cpa_currency. Pokud ten den v child tabulce nebude tak nejbližší starší.
- platební podmínky - vazba do cin_payment_cond, default se dotáhne ze dpa_party
- datum splatnosti - pokud jsem se zákazníkem domluven na konkrétní datum splatnosti, tak abych nemusel počítat tak zadám sem, default bude vždy null. a datum splatnosti se bude brát takto:
nvl(datum_splatnosti, datum_vystavení + platební podmínky)
- sleva/prirazka celkem(numeric) - procentuální sleva na celou zakazku
- cena_bez_dph(numeric) - v MD toto pole neexistuje a počítá se funkcí. ale je s tím strašně problémů podle systému jak je nastavený zaokrouhlování atd. Pokud je to číslo jasně dané v DB tak se zobrazí na FA případně přenese tak do účetnictví. my budeme na Volvu přenášet do Scaly.
- castka_DPH (numeric) - je to číslo které se může skládat až ze tří sazeb 21, 15, 10 ale nevím zda použít na hlavičce, nemám v tom jasno
- cena_celkem(numeric) - součet dvou předchozích, zase nevím zda na to dělat pole, přijde mi zbytečné
- interni_poznamka(varchar)
- poznamka(varchar)
- vazba do dokumentů(abych si mohl k FA dotáhnout elektronické dokumenty), taky se sem uloží PDF vystavené FA
- středisko - vazba do nové tabulky středisek(zde u Volva se podle toho na FA dotahuje logo Renault nebo VOLVO), u jiných zákazníků se podle střediska počítaj obraty, vypočítávaj slevy, např středisko Servis, Prodej, Vedení.
- číslo objednávky(varchar) - to je číslo objednávky které chce zákazník uvádět na FA aby si u sebe v systému mohl FA párovat
- objednávající(varchar) - možnaost dotáhnout z kontaktních osob, ale i zadat vlastní string bez vazby
- vystavil - vazba do uživatel

Je spousta dalších polí co budou potřeba, ale ty Volvo nevyužívá, tak je budem přidávat postupně. Dále jsou pole na zamyšlení, které by sloužily pro uchování informací o zákazníkovi, když se mu změní FA údaje. Na druhou stranu, pokud by se uchovávaly všechny PDFka z vystavené FA, tak si nemyslím, že by bylo třeba uchovávat původní v dalších polích.

Samotné vystavení FA bych si představoval takto: 
- že si uživatel vše naplní. Hlavičku i položky a poté na hlavičce klikne na uzavřít. Poté by vyskočilo okno s navrhnutým novým VS(pokud jej upraví na jiný než navrhnutý, tak se řada VS nebude inkrementovat o 1), datumem vystavení, DUZP. to by mohl upravit a poté jakmile by dal ok, tak se celý doklad zamkne a do dokumentů se uloží PDF. To si uživatel bude moci zobrazit aby viděl jak vypadá případně vytisknul, ale není to nutné. některé FA odchází automaticky emailem a není třeba je tisknout.
- Oprávněné osoby budou moci doklad zase odemknout udělat úpravy a zase uzavřít stejným postupem jako výše, jen VS by se nabídl už ten použitý. Zase by se generovalo nové PDF. Z tohot důvodu si nemyslím, že je potřeba si uchovávat info o odběrateli.
- Ještě k uzavření, nevím zda oddělit dobropisy a FA nebo to mít v jednom a dvě tlačítka uzavřít FA vs. uzavřít dobropis.
- a ještě k tomu bude nutná funkce zkopíruj doklad, která by vytvořila kopii puvodniho vcetne polozek. samozrejme neuzavrenou...

#### Polozky FA
- vazba do ciselniku zbozi
- vazba do dpr_vehicles
- cislo zbozi(varchar) - sem se dotahne jako default cislo zbozi z cislelniku zbozi/sluzeb, ale bude mozne upravit. Někdy nechci aby zákazník věděl pod jakým číslem to mám vedené v systému(VOLVO nepoužívá)
- nazev zbozi/sluzby(varchar) - stejna logika jako cislo zbozi
- mnozstvi(numeric)
- cena za jednotku(numeric)
- sazba DPH - ta se bude dotahovat podle toho zda je zakazka zahranicni = 0(ale muze byt i s DPH), nebo tuzemska, pote se sazba dotahne jako default z cisleniku zbozi/sluzeb
- castka DPH(numeric) - to uz by bylo mnozstvi * cena * sazba DPH
- sleva na polozku(numeric) - pak nevim zda nemit jeste pole cena za jednotku po sleve?
- mnozstevni jednotka - vazba do ciselniku, default z ciselniku zbozi/sluzeb, ale volvo nepouziva

Chtel jsem pripojit PDFko pro predstavu, jak vypada FA VOLVA, ale hlasilo mi to, ze to nejde nacist... :-( posilam emailem.

**Comment by jzelenka** [comment]
ciselnik zbozi (dpr_product) bude hiearchicky, pres vazbu dpr_product_rel, kde dpr_product_rel_type = COMPONENT  (jine jsou treba OBSOLENCE, INCOMPATIBILITY apod). 

Takze v dpr_product budou jak sluzby, tak balicky, kde balicek se sklada z nekolika sluzeb.
Ok?

Na fakture (radcich faktury) volva pak budou balicky nebo sluzby?

O tech sluzbach a balickach jsi toho moc nenapsal...

**Comment by milant007** [comment]
Uz pisu strucne z telefonu
1 polozka fa bude vazba do auta a vazba do balicku(sluzby, je to to same). Takze v zauzoo bude tolik polozek, kolik je radku na tech fa od 2. Stranky, co jsem posilal emailem. Prvni strana fa ukazuje sumy jednotlivych balicku/sluzeb

**Comment by milant007** [comment]
#### Balicky a sluzby, cenotvorba
- kazde auto ma prirazene balicky(sluzby). jedna se o tabulku s vazbou do dpr_product and dpr_vehicles. V teto tabulce je jeste platnost od(od kdy se ma fakturovat - v priade null vzdy). Dale je tam cena. Ta se vyplnuje pouze v pripade, ze se lisi nez globalni cena za balicek pro zakaznika, ktera je ulozena v jine tabulce. Toto je specifikum pro VOLVO.
- cena za balicek(sluzbu) pro vybraneho zakaznika. je to tabulka, ktera ma vazbu dpa_party a dpr_product, cena, platnost od. Toto je tabulka, ktera se bude resit pro vsechny jako STD reseni, protoze se jedna o uchovani ceny za zbozi/sluzbu pro konkretniho zakaznika.
- co se cenotvorby tyce, tak se jedna o docela slozitou hierarchii jak se konecna cena ziskava a nevim zda to mit promyslene uz pri vytvareni tabulky indiv cen zakaznik - zbozi.
- pokud balicek/sluzba prirazeny k autu spada do periody kdy generuji FA, tak se vytvari jako jedna polozka teto FA. cili jestli mam flotilu 10 aut a na kazdem aute je prirazeno 5 balicku, tak se mi vygeneruje 50 polozek FA. Na report FA se to pak sgrupuje, dalsi strany reportu(priloha) jsou pak 50 radku.
- pri vytvoreni polozky se cena nacita nasledovne. divam se na indiv cenu za balicek na tomto aute, pokud neni divam se na cenu za balicek pro tohoto zakaznika, pokud neni, divam se na cenu za balicek pro skupinu zakazniku kam spada tento zakaznik, pokud neni, divam se na zakladni cenu za balicek/sluzbu.

**Comment by jzelenka** [comment]
[3698_RAKOTRANSDOPRAVACZsr_email.pdf](https://github.com/zauzoo/db/files/13059/3698_RAKOTRANSDOPRAVACZsr_email.pdf)
[3733_BCLOGISTICSsro_email.pdf](https://github.com/zauzoo/db/files/13060/3733_BCLOGISTICSsro_email.pdf)

**Comment by milant007** [comment]
pro predstavu pridavam prnscr jak jsou balicky prirazeny k urcitemu autu:

![error kopie](https://cloud.githubusercontent.com/assets/13977376/10484023/fb0f54a6-7282-11e5-979b-ec7a392dee5b.JPG)

**Comment by jzelenka** [comment]
* Do faktury dam i vazbu do Party - dodavatel. Tj. zavede se Volvo CR do party. Nemusi to byt nikde moc videt.

* faktura bude mit krome currency, jeste sloupec localCurrency, to bude ted vzdy CZK, aby pak u vice zemi, bylo vzdy jasne co to je.

* to tabulky tenant_id se prida, localCurrency + vazba do party (Volvo CR) - podle toho se bude na fakture predvyplnovat dodavatel

**Comment by jzelenka** [comment]
>datum splatnosti - pokud jsem se zákazníkem domluven na konkrétní datum splatnosti, tak abych >nemusel počítat tak zadám sem, default bude vždy null. a datum splatnosti se bude brát takto: >nvl(datum_splatnosti, datum_vystavení + platební podmínky)

Radeji bych aby datum splatnosti bylo vzdy vyplnene. Predvyplnit podle platebnich podminek (datum_vystavení + platební podmínky) s moznosti editace.

**Comment by milant007** [comment]
Datum Splatnosti - jo, muze to tak byt. ale pri zmene platebnich podminek(napr. ze 14 na 21) se datum prepocita automaticky. pak uz se muze rucne menit jak kdo chce. ale jakmile se zase zmeni platebni podminky, tak datum zase dopocitam.

**Comment by jzelenka** [comment]
ok, to uz jsou pravidla pri rucni editaci faktury, to tak samozrejme muze byt.... 
Jde o to aby napriklad report nebo gridConfig faktur po splatnosti byl jednoduchej.

**Comment by jzelenka** [comment]
Daval bys pole cena_za_jednotku a mnozstvi a mnozstevni jednotka vzdy povinne?

tj. u polozek, kde mnozstvi nema moc smysl bude vzdy
mnozstvi = 1
cena_za_jednotku = celkova_cena (pominu ted slevy a DPH)
mnozstevni jednotka = kusu

Ja si jo....

**Comment by milant007** [comment]
ANO, to musi byt vzdy vyplnene. 
Jedine pripad, kdy by polozka FA byla neco jako textova(V MD ta moznost je), tak by se o tom mohlo premyslet. ale textovy veci bych oddelil do poli kam patrej texty.

**Comment by jzelenka** [comment]
s tim pocitam ze bude moc byt textova, bez vazby na produkt a vozidlo (jeste tam mam typ polozky, podle toho se to pozna.)
Ale i u ni by mohly byt vsechny ty pole povinne, v GUI by se treba skryly a pak vyplnili automaticky pri ulozeni. Aby pak clovek pri praci s daty nemusel premyslet jake pole jsou vyplnene

**Comment by jzelenka** [comment]
Presnost peneznich castek - v databazi davam 4 mista.

**Comment by milant007** [comment]
ANO, nekde ale nemusi stacit ani sest mist, na heiru maj i na 7. bud se to bude postupne navysovat podle potreby nebo v MD je pole "cenova hladina" a tam se dava o kolik desetinnych mist se ma cena posunout. pak muze byt cena i na 10 desetinnych mist.
- proc tak presna cena? opet v tom maj prsty EURa. cenik pro zakazniky vydam pouze v EURech a tak to mam zadane v systemu. a ta cena je na 4 desetinna mista. pak si to zakaznik objedna ale chce FA v CZK a tak se cena v EUR na 4 desetinna mista vynasobi kurzem, ktery byva na 3 desetinna mista. A zakaznici jsou vselijaci a nekteri proste nezkousnou ze by se to mohlo zaokrouhlit a tak se musi cena zobrazovat takhle. :-(

**Comment by jzelenka** [comment]
To pole cenova hladina znamena, ze ceny jsou bezrozmerne (bez desetinnych mist) a na skutecnou castku ty cisla posouva ta cenova hladina?

**Comment by milant007** [comment]
ne, STD jsou na dve desetinna mista. a napr. kdyz chci na 5 desetinnych mist, tak do cenove hladiny dam 3

**Comment by jzelenka** [comment]
jo takze cenova hladina ridi zaokrouhlovani.
a castka je vzdycky skutecna.

No tak dame pocet desetinych mist klidne 8, to je fuk
jeste napis kde ta cenova hladina bude nastavena = tenant?, customer?,  invoice?

asi ji nazvu monetaryRounding a bude vzdy nastavena (takze bude na tenatovi, pak muze byt nekde jinde override, treba zakaznik)

tzn na tenantovi bude pole monetaryRounding a vetsinou bude mit 2.

Pozn: Pri schedulingu jobu se bude nastavovat tenant...

Ok?

**Comment by milant007** [comment]
idealni, v tenantovi bude monetaryRounding(vetsinou 2)  a to se bude defaultem prenaset do FA. pokud budu chtit udelat FA na presnejsi castku, tak cislo zvysim nebo snizim a podle toho si mi zobrazi pocet mist za desetinnou carkou.

**Comment by jzelenka** [comment]
je to hotove.
Popis viz wiki,
na popis jednotlivych policek musis do zdrojaku, ktere jsou odkazovane z wiki

**Comment by jzelenka** [comment]
v tech zdrojacich ma smysl i poradi policek jak jdou za sebou (treba u castek na fakture), hibernate kdyz z toho generuje DDL tak to bohuzel rozmrda...

**Comment by milant007** [comment]
takze pri importu dpr_product mam nasledujici:
- postradam vazbu do DPH, ta se pak prenese do polozky FA
- unit_of_measure je varchar(255), to nechapu kdyz v cpr_unit_of_measure je varchar(10) a je na to vazba.
- co je pole gtin?

**Comment by milant007** [comment]
potrebuji rozsirit tabulku dpr_product_vehicle_asoc:
- Datum Upozorneni - datum kdy prijde email poverene osobe - pri zmene se Datum odeslani upozorneni nastavi na null
- Text upozorneni(varchar 200) - text co bude v tom emailu = pri zmene se Datum odeslani upozorneni nastavi na null
- Datum odeslani upozorneni - aby se poslalo pouze jednou
- Datum odeslani zahajeni platnosti - je to sice nesmysl, protoze by to slo vyresit pres Datum upozorneni, ale proste si to vydupali. Jedna se o info, ze se odeslala informace o tom za byla zahajena platnost balicku. Oni na to nasledne upozornuji zakaznika, ze je zacnou nove fakturovat za toto auto a tento balicek.
- a pouze dotaz, my do gridu/formulare dotahnem moznost vyplnit cenu primo? cili ze napojime dpr_price_component pres vehicle_id a product_id ?

**Comment by jzelenka** [comment]
* DPH pridano (technicky to nedelam cizim klicem do `cin_vat_rate`, protoze bych pak v jave nemel cislo ale objekt (kvuli hibernate) a ja chci cislo, prijde me to jednodussi. Ale v GUI bude vyber z ciselniku cin_vat_rate. Chci ho mit not null, tak jsem dal vsude 21%.
* to je chyba, opraveno
* gtin je https://en.wikipedia.org/wiki/Global_Trade_Item_Number , editel to vsude pouziva, taky je to asi cislo z caroveho kodu. Volvo nemusi pouzivat, nemusime ani davat na formular....

**Comment by jzelenka** [comment]
ad to posledni) - asi to tak muze byt...

ad to predtim) - zitra - udelam to nejak obecne, samostatne (nebudu to davat na dpr_product_vehicle_asoc). Je to podobna vec jako dpr_price_component ...

**Comment by milant007** [comment]
Hlavicky FA tam jsou nasypane do din_invoice. Zitra budou polozky a jeste par hlavicek FA pribude protoze import do Postgre stale bezi. :-(
- Nerozklicoval jsem jedine pole u FA: invoice_status ? Dal jsem tam closed.
- a jeste jedna vec na zamysleni, informace o dodacim listu by spis mela byt vazba primo na dodak. Je celkem normalni ze se udela vice dodaku a vystavuje jedina FA. Neni to ale pripad VOLVA, ty dodaky nemaj vzhledem k tomu ze fakturujou pouze sluzby.

**Comment by jzelenka** [comment]
> Nerozklicoval jsem jedine pole u FA: invoice_status ? Dal jsem tam closed.

Je to nějaký stav faktury, nyní to mohou být hodnoty OPEN, CLOSED, můžeme tam dát něco jiného.
Fakticky se mě jedná o to umožnit uložit rozpracovanou fakturu - to mělo být to OPEN ..
CLOSED na odeslaných fakturách je dobře.
Můžeme tam vymyslet jiné hodnoty, třeba:
- OPEN - rozpracovana faktura, lze editovat
- CLOSED - hotova faktura, nelze editovat
- REOPEN - znovu otevrena faktura k oprave treba, lze editovat
- SEND ? - pokud bychom chtěli sledovat že faktura byla odeslána.

Trochu to souvisí se sledováním změn.... 

>a jeste jedna vec na zamysleni, informace o dodacim listu by spis mela byt vazba primo na dodak. Je celkem normalni ze se udela vice dodaku a vystavuje jedina FA. Neni to ale pripad VOLVA, ty dodaky nemaj vzhledem k tomu ze fakturujou pouze sluzby.

No jo, to jsem opsal z editelu.... teď dodáky dělat nebudeme, takže to mám vyhodit? S tím, že jednou to bude udělaní jinak?

**Comment by milant007** [comment]
u tech dodaku je to jedno, tak tam bude null, az je budem resit. tak se to predela.

Hlavicky FA uz jsou tam kompletni. nepreneslo se pouze par FA kde mezitim pribyli novi zakaznici a mne se to ted nechtelo aktualizovat.

Jen pro info se jeste vratim k dpr_products.GTIN(neni to pripad VOLVA). GTIN muze byt na hlavicce, ale pro material jako takovy je treba mit specialni tabulku na cisla zbozi. Dodavatele velice casto radi meni oznaceni svych vyrobku kvuli kopirovani originalnich dilu od ostatnich vyrobcu. takze po nejakem case se nasbira nekolik GTINu a zakaznici co si to pak chodi kupovat diktuji to cislo, pod kterym to tehdy koupili, takze v DB musi byt vse aby se to naslo. Stejne tak mohu temto vyrobkum ja davat vlastni EAN pro svou vlastni skladovou evidenci. Take tomu obcas musim priradit cislo pod jakym si to vede ve sve DB odberatel, pokud je dostatecne silny na to, aby si mohl diktovat, tak musim na FA uvadet jeho cislo a pod nim to i objednava. Podle vsech techto cisel musim umet vyhledat tu konkretni polozku.

**Comment by jzelenka** [comment]
> GTIN

dobre, chapu, tak co ted? vyhodit GTIN, nechat tam jen productNumber a s tim ze zvlastni tabulka se dodela pozdeji?

**Comment by milant007** [comment]
asi bych to zatim vyhodil, ale toto je na delsi diskusi. ted mi jeste Jindra rika, ze stejny vyrobek muze mit jiny EAN kdyz prijimam paletu, nebo kdyz prijimam baleni. tim se spravne prepocte mnozstvi pri naskladneni. Na druhou stranu vzdy je nejaky gtin hlavni, ale asi bych to resil prioritou 1 v child tabulce tak jako mame obchodni zastupce.

**Comment by jzelenka** [comment]
Dobre, uz je zrusen, productNumber  nechavam.

mas neco k tomu invoice_status  ?

**Comment by milant007** [comment]
invoice_status: nejak s tim nemam zkusenost. mne by to napadlo resit jinak, ale byt to tak nemusi, treba ten status bude stacit, pripadne zavolej. ja bych zalozil column closed a tam mel bud timestamp = closed, kdyz je null, tak je open. SEND bych resil pres extra tabulku, kde bych si uchovaval informaci kdy se poslalo, co se poslalo(FA, DODAK, NABIDKA), kdo poslal(Uzivatel nebo prip. automat). Automat by posilal FA v pripade ze closed > max(send) v posilaci tabulce. Nebo mozna by stacil column SEND s timestamp na hlavicce FA?
Jeste mi ted doslo ze se na hlavicce nebo nejake externi tabulce musi ukladat datum prenosu do ucetnictvi. aby se zase pripadne pri uprave kdy se FA znovu otevre a uzavre poslalo znovu.

**Comment by jzelenka** [comment]
zatim to tam necham, bude to duplicitni (pro nejake rychle jednoduche vyhledani) k nejake tabulce stavu / akci nad fakturou, kde budou ty datumy.

**Comment by milant007** [comment]
Jsou tam nasypany polozky FA. 
Asi by nebylo od veci, kdyby se nekdo pustil do layoutu FA. template te FA bude nekde v blobu v DB? asi by to chtelo, protoze kazdej klient VOLVA bude chtit vlastni design.
Bud by na tom delal Jindra, ktery pripravoval cely report pro MDcka, nebo Martin za Jindrovi asistence. Tak na to pak zalozis asi novy issue kde popises technologii a how to?

**Comment by milant007** [comment]
- Naimportoval jsem cenove hladiny 1 a 2 do dpr_price_component, vic jich ve Volvu neni
- Naimportoval jsem dpr_product_vehicle_asoc
- Jeste zbyva presypat ty upozornovani na balicky z toho duleziteho. Pak uz tam jsou jen nejaky drobnosti na presypani.
- Napisu select pro tvorbu layout te FA nebo by to bylo zbytecny?

**Comment by jzelenka** [comment]
Zbytecny, zadny select tam nebude. Nacteni z db do objektu zajistuje hibernate.

**Comment by jzelenka** [comment]
Jak je urceno komu ma upozorneni chodit?

U zakaznika (ktery vlastni vehicle), mame owner_id, coz ma byt login uzivatele, ktery se o zakaznika stara. To by se na to hodilo? Je to nevyplnene...

**Comment by jzelenka** [comment]
Neni naimportovan `din_invoice_vat_recap` - rozpad DPH podle sazeb.

**Comment by milant007** [comment]
Sepisu pro predstavu vsechno co ted automatikou chodi emailem:
- upozorňování na balíčky. uživatel si zadá kdy to má přijít a text. zadává se u konkrétního balíčku přiřazeného na auto. email chodí obchodnímu zástupci2(takže musím předělat skript na pořadí při importu) a na univerzální email volva(asi muzem tahat z kontaktnich informaci na ownera).
- email na zacatek platnosti balicku u konkretniho auta, ted chodi stejnym principem jako bod vyse, ale podle me by to melo chodit na zakaznika aby o tom vedel, a kdyz to bude chtit resit tak se ozve na Volvo. Ale to musim probrat s nekym z volva.
- email na zruseni balicku. Pokud se zrusi balicek(deaktivuje cely auto nebo jen jeden vybrany balicek)  do 6 měsíců od založení, jde email na spravce(asi taky univerzalni email). jde o to, ze obchodaci dostavaj provize z tech balicku, tak aby jim je sebrali
- email po zalozeni zakaznika. vysleduji jake balicky tam jsou podle strediska(VOLVO or RENAULT), a podle toho posilame email s odpovidajicim textem(VOLVO / REANULT, pokud obsahuje oba druhy jdou dva maily) podle strediska. prilohy jsou PDFka podle prirazenych balicku + nejake univerzalni. Dale v tom emailu jdou informace o prihlaseni do web aplikace. Tyto prihlasovaci udaje se generuji pri zalozeni zakaznika automaticky v MDckach(a my jsme je zatim nemigrovali do ZZ).
- posilaji se automaticky FA, tam kde to ma zakaznik nastaveno
- posila se textak ucetni s vystavenymi FA co nebyly jeste prevedeny do účta

**Comment by milant007** [comment]
`din_invoice_vat_recap` - je to tam

**Comment by jzelenka** [comment]
`dpr_product.product_type` je enum  s hodnotami GOOD a SERVICE. 
Vlastni typ produktu jsem nemel.

Takze jsem zavedl ciselnik `cpr_product_category` a vazebni tabulku na dpr_product `dpr_product_category_asoc`, protoze produkt muze byt ve vice kategoriich.

ty DYNA a OPTI dej do cpr_product_category, category_type dej treba USAGE (zase enum).

product_type jsem vsude updatnul na SERVICE

Vysvetleni kdy je neco enum a kdy ciselnik:
- ciselnik - editace mozna z GUI, uzivatel si sam bude pridavat...
- enum - natvrdo v java kodu, bud kdyz se moc nemeni nebo kdyz je zmena spojena s programovanim, pr. TYP_ALGORITMU. Nebo kdyz se me nechce delat ciselnik :)

aktualizoval jsem wiki.

**Comment by jzelenka** [comment]
Stejne tak jsme musel aktualizovat din_invoice_item:

       update din_invoice_item set item_type = 'PRODUCTITEM' where item_type = 'PRODUCT';
       update din_invoice_item set item_type = 'PRODUCTVEHICLEITEM' where item_type = 'PRODUCT & VEHICLE';

tady tedy nastesti slo jen o syntaxi.

Enumy poznas tak, ze vypada podezrele jako vycet hodnot ale neni to vazba do ciselniku.
V java tride pak je to videt (na java tridy davam odkazy z wiki).  Pokud nedam do commentu povolene hodnoty, tak se musis podivat do tridy toho enumu - je v package enums, takze treba `PRODUCTCATEGORYTYPE` coz je trida pro enum `ProductCategory.categoryType` je v  adresari `product/enums`

**Comment by milant007** [comment]
Product category jsem doplnil.

enum u invoice_item jsem vycetl z komentare: `typ radku faktury (FREE, PRODUCT, PRODUCT & VEHICLE)`

**Comment by jzelenka** [comment]
no jo no, opravim jsem komentar :anguished:

**Comment by milant007** [comment]
dle vcerejsi domluvy jsem zalozil nove role a priradil kontaktni osoby, tabulku dpa_party_feature promazal. Upravil jsem importni skripty.

**Comment by jzelenka** [comment]
@milant007 @krivohlavek 

prejmneoval jsem hodnoty v invoice_status:
OPEN -> CONCEPT
CLOSED -> ISSUED
CANCELED  (novy status)

je to v aktualizovane v databazi a deploynuta aplikace, upravte si skripty

**Comment by jzelenka** [comment]
zaviram, snad uz to je vse hotovo.
