### ISSUE TITLE
Unique index na IČ, nové pole IČ DPH

### ISSUE THREAD

**Issue by milant007** [zauzoo/db#4]
- je potřeba předělat unique index na pole IČ v dpa_party. IČ musí být unique v kombinaci s tenantem. Budu zavádět slovenskou a maďarskou pobočku volva a přitom v CZ již slováci existují.
- pro slovenskou verzi/tenanta je potřeba vytvořit nové pole "IČ DPH". Slováci totiž používají IČ, DIČ a IČ DPH. Toto pole má asi smysl zobrazit pouze v tenantu SK
- co se pole, které se zobrazuje pouze v nějakém tenantovi týče, tak to nebude jediný případ. Už teď vím že Maďaři mají taky své speciality(ve fakturaci) a pole co se v CZ ani SK nepoužívají. Píšu o tom proto, zda by tato informace neměla být někde přímo v ZZ? A že i pole by se podle toho zobrazovaly?

**Comment by jzelenka** [comment]
Je to tam, pole se jmenuje ico_dph
Kde se bude nastavovat zobrazeni dle tentanta si jeste rozmyslim

**Comment by milant007** [comment]
Jen pro Info: zalozil jsem tenanta HU a v party jsem zaloziil Volvo SK a Volvo HU vcetne adress a bankovnich uctu a prolinkoval do tabulky tco_tenant. Takze paticka reportu je mozna nacitat z DB(ted je natvrdo). To se uz Jindra domluvi s Honzou.
Dal jsem git push na nove skripty.
