### ISSUE TITLE
Tabulka na číselné řady

### ISSUE THREAD

**Issue by milant007** [zauzoo/db#5]
Je potřeba vytvořit tabulku na číselné řady

- je potreba mit na mysli, ze budou ciselne rady i pro ostatni doklady (dodaky, nabidky, dobropisy, atd.)
- musi byt v te tabulce datum platnosti. aby se ciselna rada prirazovala podle datumu dokladu a uzivatel si mohl pripravit ciselnou radu klidne i na nekolik let dopredu.
- ciselna rada muze mit vice okruhu pro 1 typ dokladu. Mockrat jsem nastavoval vice ciselnych rad pro fakturaci v zavislosti na stredisku. U Volva to tak neni, ale kdyby to chteli tak by tio napr. fungovalo tak, ze by rekli, ze chteji ciselnou radu pro Dynafleet(VOLVO) a pro Optifleet(RENAULT).
- jedna ciselna rada muze slouzit vice typu dokladu. Opet se jedna o priklad fakturacni rady, kde zakaznik muze chtit stejnou radu pro dobropisy, faktury, danove doklady o prijeti platby(po zaloze) zaroven, ale muze je chtit i oddelit.
- a jeste me napadlo, ze napr. fakturace by asi mela mit  vlastni interni radu. Toto interni cislo by se melo prirazovat uz pri zalozeni zakazky. Jde o to, ze kdyz nekdo necha neco rozpracovaneho a bude si to predavat s kolegy, tak aby mel nejaky unikatnu klic ktery kolegovi preda. Cislo FA jeste nebude pridelene.

**Comment by jzelenka** [comment]
Udelam zvlast tabulky ciselnych rad pro jednotlive entity (Faktura):
ciselna rada faktury bude vybrana:
1. dle platnosti podle invoiceDate
2. dle tenanta
3. dle invoiceType (faktura, dobrobis) - nemusi byt zadane
4. dle profitCenter - nemusi byt zadane

vypocet vlastniho cisla bude vypadat takto:
konstantaMax10 +   poradove cislo doplnene zleva nulama na delku X , kde X je maximalne 10.

Kazda rada bude mit u sebe ulozeno:
konstanta
poradoveCislo - to se inkrementuje pri kazdem sliznuti
padding - to je to X.

Takze  treba moje konvence 2016001 bude nastavena takto:
konstanta = 2016
padding = 3

OK?

**Comment by milant007** [comment]
Vyber rady ok, MD to maji uplne stejne. Jedine co maji navic jeste vyber podle uzivatele, ale to jsem nikdy nepouzil, vzdy jen tyto 4 moznosti. U te trojky pak pribude dodaci list, vydejka atd...

Generovani cisla taky ok, jen ta konstannta aby mohla byt i pismeno, na konci tedy prevest tu incrementovanou cast na string a spojit.

**Comment by jzelenka** [comment]
hotovo,
ja u sebe to testoval s radou:

insert into tin_invoice_number_gen(invoice_number_gen_id, next_suffix_number, padding, prefix_constant, tenant_id, valid_from, valid_to)
    values (1, 1, 4, '2016', 1, '2016-01-01', '2016-12-31');

prvni liznute cislo faktury pak bude 20160001
