### ISSUE TITLE
Insert new user

### ISSUE THREAD

**Issue by milant007** [zauzoo/db#6]
Muzes prosim zalozit uzivatele jurajda / Volvo2015 ?

Nebo mi napsat jakej hashovaci algoritmus používáme a ja si to tam insertnu sam

**Comment by jzelenka** [comment]
GUI na uzivatele je hotove, mely by tam byt opravene chyby ktere jsme videli vcera.
kdyz zadas login s mezerami a diakririkou, tak mezery se vyhodi a diakritika zrusi a prevede se na mala pismena:
Petr Novák => petrnovak
