### ISSUE TITLE
dpa_party.full_name je pro fyzicke osoby vyplnene first_name + last_name

### ISSUE THREAD

**Issue by jzelenka** [zauzoo/db#7]
Potrebuju to pro zjednoduseni spousty veci v gridech.
V GUI to videt nebude nebo read-only (kdyz vyplnujes Kim Ir Sen tak je lepsi full name nez first a last name).
Aktualizovat se to bude pri save z aplikace, ale pri migraci se spusti nize uvedeny select (ted uz jsem ho spustil):

    update dpa_party 
    set full_name = case when first_name is not null and last_name is not null then (first_name  || ' ' || last_name) when first_name is null then last_name when last_name is null then first_name end 
    where full_name is null and (first_name is not null or last_name is not null);

Tak si ho pridej do skriptu

**Comment by milant007** [comment]
Skripty upraveny, dal jsem git push. Update jsem zjednodusil i kdyz to je jedno:

    update dpa_party
    set full_name = trim(coalesce(first_name,' ') || ' ' || coalesce(last_name,' '))
    where full_name is null and (first_name is not null or last_name is not null);
