### ISSUE TITLE
DPH na produktu

### ISSUE THREAD

**Issue by milant007** [zauzoo/db#8]
Musí se upravit datový model na dpr_product. Nelze tam mít pole vat_rate vzhledem k tomu, že tenant_id má hodnotu 0, protože CZ ma 21% SK má 20% a HU má 27%. Takže asi vazba do nějaké tabulky DPH sazeb?

**Comment by jzelenka** [comment]
Je nejaky duvod proc nema produkt tenant_id <> 0 ?  Nejaka vyhoda ze jsou produkty jen jednou?
dpr_vehicle a dpr_product_vehicle maji tenant_id <> 0.

**Comment by milant007** [comment]
Právě mi poslali podklady z HU. takže tento měsíc chtějí fakturovat. :-( pro me nastesti jen balik optifleet = renault, kde je toho malo. ALE DPH je v HU rozdilny, takze se musime poradit co s tim. Pokud bychom nestihali, nacpu to DPH do faktur skriptem takovy jaky ma byt.

**Comment by jzelenka** [comment]
Je to tam:
- DM dle https://github.com/zauzoo/app/wiki/DPH
- naplnene CR
- podarilo se zachranit sloupec vatRate na gridu produktu a produktu na vozidle
     - u CT je 21%, SK spravne prazdne

**Comment by milant007** [comment]
Je to tam pro vsechny zeme.

A jeste kdyz jsem nad tim premyslel, tak na hlavicce faktur by mela byt moznost zvolit VAT_RATE. Standardne bude by to pole bylo null, a sazba by se dotahovala logicky ze sazeb. Akorat tam musi byt logika, ze kdyz se jedna o zahranicni to znamena, ze zeme v tco_tenant nesouhlasi se zemi kam fakturuji dotahne se nulova sazba. ale porad v tomto pripade muze byt pole VAT_RATE na hlavicce prazdne. ALE muze nastat, ze chci z nejakeho duvodu nacenit DPH podle sebe(prenesena danova povinnost) a pak by tam mela byt moznost to vybrat a nahodit na vsechny polozky tuto sazbu. kdyz ji pak odstranim dam na null zase logikou DPH vratim jake ma byt(menim pouze pokud je faktura neuzavrena). Mohou nastat i 3 sazby na jedne fakture: napr. jidlo GULAS - take away 15%, slepici vyvar 21%, tocene pivo 10% :-)

**Comment by jzelenka** [comment]
Moc to nechapu, k cemu bude VAT_RATE na fakture?
pouze k vynulovani pri exportu?
a pak kdyz to budu chtit vratit, tak vrazim na polozky jednu VAT_RATE, coz muze byt spatn (gulas, vyvar, pivo) ?

Neslo by dat na fakturu jen policko Vynulovat DPH, ktere je vynuluje a Obnovit DPH, ktere ji obnovi spravne (= ruzne dle sazby) ?
Plus k tomu vynulovani by dochazelo automaticky podle "ze zeme v tco_tenant nesouhlasi se zemi kam fakturuji"

Btw. udelal jsem v GUI editaci VAT_RATE na pruduktu.

**Comment by jzelenka** [comment]
policko Vynulovat DPH => tlacitko

**Comment by milant007** [comment]
asi se na to ted vyser, budem to resit az to prijde
