### ISSUE TITLE
vat_rate odkaz v din_invoice_item

### ISSUE THREAD

**Issue by jzelenka** [zauzoo/db#9]
Pridal jsem do din_invoice_item odkaz na cin_vat_rate:

potrebuju ho kvuli GUI bude to fungovat takto:
1. uzivatel (u free polozky) vybere vat rate z ciselniku (jako ted na produktu)
2. sazba DPH se nastavi podle aktualniho data z cin_vat_rate_value
3. pri vystaveni faktury se znovu nastavi sazba z cin_vat_rate_value podle DUZP (aby to fungovalo na prelomu roku pri zmene sazby).

uprav si plnici skripty, pak to zavri.

    alter table din_invoice_item
        add column vat_rate_id int4
 ;

update din_invoice_item set vat_rate_id = cv.vat_rate_id
from cin_vat_rate cv, cin_vat_rate_value cvv, tco_tenant t
where  cv.vat_rate_id = cvv.vat_rate_id and cvv.vat_rate = din_invoice_item.vat_rate and din_invoice_item.tenant_id = t.tenant_id
  and t.vat_rate_country = cv.country;

   alter table din_invoice_item
        alter column vat_rate_id set not null
 ;

    alter table din_invoice_item
        add constraint fk_din_invoice_item_06
        foreign key (vat_rate_id)
        references cin_vat_rate
 ;

**Comment by milant007** [comment]
skripty upraveny a pushnuty...
